<a href="https://colab.research.google.com/github/abhishekbhat11/DSML/blob/main/Task1_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
Arr1 = np.array([1,2,3,2,3,4,3,4,5,6])

In [4]:
Arr2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [5]:
b=Arr1.reshape(5,2)
b

array([[1, 2],
       [3, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

In [6]:
c=np.intersect1d(Arr1,Arr2)
print(c)

[2 4]


In [11]:
for i in range(0,len(Arr1)-1):
  if Arr1[i] in Arr2:
    Arr_new=np.delete(Arr1,i)
print(Arr_new)

[1 3 3 3 5 6]


In [14]:
np.isnan(Arr1)

array([False, False, False, False, False, False])

In [15]:
np.isnan(Arr2)

array([False, False, False, False, False, False, False, False, False,
       False])